version: 2
updates:
  # Update GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update Python/Django dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"